language: node_js
node_js: "8"
env:
  global:
    - PKG_CACHE_PATH=${TRAVIS_BUILD_DIR}/.pkg
    - BUILD_PATH=${TRAVIS_BUILD_DIR}/build/${TRAVIS_REPO_SLUG}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}
cache:
  directories:
    - node_modules
    - ${PKG_CACHE_PATH}
script:
  - npm test
  - npm run coverage
before_deploy:
  - echo "SENTRY_URL=${SENTRY_URL}" > .env
  - echo "COUNTLY_URL=${COUNTLY_URL}" >> .env
  - echo "COUNTLY_APP_KEY=${COUNTLY_APP_KEY}" >> .env
  - mkdir -p ${BUILD_PATH}
  - npm run package
  - find ${TRAVIS_BUILD_DIR}/build -name 'fetchforge-*' -print -exec zip -j '{}.zip' '{}' \; -exec rm -f '{}' \;
  - find ${TRAVIS_BUILD_DIR}/build -name 'fetchforge-*.exe.zip' -print -exec sh -c 'mv {} $(echo {} | cut -f 1 -d .).zip' \;
  - mv ${TRAVIS_BUILD_DIR}/build/fetchforge-*.zip ${BUILD_PATH}/
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      tags: false
      all_branches: true
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file: ${BUILD_PATH}/fetchforge-*
    skip_cleanup: true
    on:
      branch: master
      tags: true
