language: node_js
node_js: node
env:
  - PKG_CACHE_PATH=${TRAVIS_BUILD_DIR}/.pkg
cache:
  directories:
    - node_modules
    - ${PKG_CACHE_PATH}
before_deploy: npm run package
deploy:
  - provider: s3
    access_key_id: ${ARTIFACTS_KEY}
    secret_access_key: ${ARTIFACTS_SECRET}
    bucket: ${ARTIFACTS_BUCKET}
    file_glob: true
    file: fetchforge-*
    skip_cleanup: true
    on:
      branch: development
  - provider: releases
    api_key: ${GITHUB_OAUTH_TOKEN}
    file_glob: true
    file: fetchforge-*
    skip_cleanup: true
    on:
      tags: true
